# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs

version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run


# jobs:
#   build:
#     docker:
#       - image: circleci/node:latest-browsers

#     steps:
#       - checkout
      
#       - run:
#           name: Install Dependencies
#           command: npm ci
#           when: always
     
#       - run:
#           name: Run cypress tests process
#           command: npm run test  
     
